// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wewatch.proto

package cloudwalker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinState int32

const (
	JoinState_ALREADY JoinState = 0
	JoinState_ADDED   JoinState = 1
	JoinState_UNKNOWN JoinState = -1
)

var JoinState_name = map[int32]string{
	0:  "ALREADY",
	1:  "ADDED",
	-1: "UNKNOWN",
}

var JoinState_value = map[string]int32{
	"ALREADY": 0,
	"ADDED":   1,
	"UNKNOWN": -1,
}

func (x JoinState) String() string {
	return proto.EnumName(JoinState_name, int32(x))
}

func (JoinState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{0}
}

type PlayerStates int32

const (
	PlayerStates_UNRECOGNISED PlayerStates = 0
	PlayerStates_PLAY         PlayerStates = 1
	PlayerStates_PAUSE        PlayerStates = 2
	PlayerStates_REWIND       PlayerStates = 3
	PlayerStates_FORWARD      PlayerStates = 4
	PlayerStates_BUFFER       PlayerStates = 5
	PlayerStates_SYNC         PlayerStates = 6
)

var PlayerStates_name = map[int32]string{
	0: "UNRECOGNISED",
	1: "PLAY",
	2: "PAUSE",
	3: "REWIND",
	4: "FORWARD",
	5: "BUFFER",
	6: "SYNC",
}

var PlayerStates_value = map[string]int32{
	"UNRECOGNISED": 0,
	"PLAY":         1,
	"PAUSE":        2,
	"REWIND":       3,
	"FORWARD":      4,
	"BUFFER":       5,
	"SYNC":         6,
}

func (x PlayerStates) String() string {
	return proto.EnumName(PlayerStates_name, int32(x))
}

func (PlayerStates) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{1}
}

type LeaveRoomResponse_LeaveRoomState int32

const (
	LeaveRoomResponse_UNKNOWN    LeaveRoomResponse_LeaveRoomState = 0
	LeaveRoomResponse_REMOVED    LeaveRoomResponse_LeaveRoomState = 1
	LeaveRoomResponse_ALREADY    LeaveRoomResponse_LeaveRoomState = 2
	LeaveRoomResponse_NOT_EXISTS LeaveRoomResponse_LeaveRoomState = 3
)

var LeaveRoomResponse_LeaveRoomState_name = map[int32]string{
	0: "UNKNOWN",
	1: "REMOVED",
	2: "ALREADY",
	3: "NOT_EXISTS",
}

var LeaveRoomResponse_LeaveRoomState_value = map[string]int32{
	"UNKNOWN":    0,
	"REMOVED":    1,
	"ALREADY":    2,
	"NOT_EXISTS": 3,
}

func (x LeaveRoomResponse_LeaveRoomState) String() string {
	return proto.EnumName(LeaveRoomResponse_LeaveRoomState_name, int32(x))
}

func (LeaveRoomResponse_LeaveRoomState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{1, 0}
}

type LeaveRoomRequest struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomRequest) Reset()         { *m = LeaveRoomRequest{} }
func (m *LeaveRoomRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomRequest) ProtoMessage()    {}
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{0}
}

func (m *LeaveRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomRequest.Unmarshal(m, b)
}
func (m *LeaveRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomRequest.Marshal(b, m, deterministic)
}
func (m *LeaveRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomRequest.Merge(m, src)
}
func (m *LeaveRoomRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomRequest.Size(m)
}
func (m *LeaveRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomRequest proto.InternalMessageInfo

func (m *LeaveRoomRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *LeaveRoomRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LeaveRoomResponse struct {
	LeaveRoomState       LeaveRoomResponse_LeaveRoomState `protobuf:"varint,1,opt,name=leaveRoomState,proto3,enum=cloudwalker.LeaveRoomResponse_LeaveRoomState" json:"leaveRoomState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *LeaveRoomResponse) Reset()         { *m = LeaveRoomResponse{} }
func (m *LeaveRoomResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomResponse) ProtoMessage()    {}
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{1}
}

func (m *LeaveRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomResponse.Unmarshal(m, b)
}
func (m *LeaveRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomResponse.Marshal(b, m, deterministic)
}
func (m *LeaveRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomResponse.Merge(m, src)
}
func (m *LeaveRoomResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomResponse.Size(m)
}
func (m *LeaveRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomResponse proto.InternalMessageInfo

func (m *LeaveRoomResponse) GetLeaveRoomState() LeaveRoomResponse_LeaveRoomState {
	if m != nil {
		return m.LeaveRoomState
	}
	return LeaveRoomResponse_UNKNOWN
}

type JoinRoomRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{2}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinRoomRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type JoinRoomResponse struct {
	JointState           JoinState `protobuf:"varint,1,opt,name=jointState,proto3,enum=cloudwalker.JoinState" json:"jointState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{3}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetJointState() JoinState {
	if m != nil {
		return m.JointState
	}
	return JoinState_ALREADY
}

type MakeRoomRequest struct {
	Tkn                  string   `protobuf:"bytes,1,opt,name=tkn,proto3" json:"tkn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeRoomRequest) Reset()         { *m = MakeRoomRequest{} }
func (m *MakeRoomRequest) String() string { return proto.CompactTextString(m) }
func (*MakeRoomRequest) ProtoMessage()    {}
func (*MakeRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{4}
}

func (m *MakeRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeRoomRequest.Unmarshal(m, b)
}
func (m *MakeRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeRoomRequest.Marshal(b, m, deterministic)
}
func (m *MakeRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeRoomRequest.Merge(m, src)
}
func (m *MakeRoomRequest) XXX_Size() int {
	return xxx_messageInfo_MakeRoomRequest.Size(m)
}
func (m *MakeRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeRoomRequest proto.InternalMessageInfo

func (m *MakeRoomRequest) GetTkn() string {
	if m != nil {
		return m.Tkn
	}
	return ""
}

type MakeRoomResponse struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeRoomResponse) Reset()         { *m = MakeRoomResponse{} }
func (m *MakeRoomResponse) String() string { return proto.CompactTextString(m) }
func (*MakeRoomResponse) ProtoMessage()    {}
func (*MakeRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{5}
}

func (m *MakeRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeRoomResponse.Unmarshal(m, b)
}
func (m *MakeRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeRoomResponse.Marshal(b, m, deterministic)
}
func (m *MakeRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeRoomResponse.Merge(m, src)
}
func (m *MakeRoomResponse) XXX_Size() int {
	return xxx_messageInfo_MakeRoomResponse.Size(m)
}
func (m *MakeRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeRoomResponse proto.InternalMessageInfo

func (m *MakeRoomResponse) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type LoginRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{7}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{8}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{9}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type StreamRequest struct {
	RoomMeta             *RoomMeta `protobuf:"bytes,1,opt,name=roomMeta,proto3" json:"roomMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{10}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetRoomMeta() *RoomMeta {
	if m != nil {
		return m.RoomMeta
	}
	return nil
}

type StreamResponse struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*StreamResponse_ClientLogin
	//	*StreamResponse_ClientLogout
	//	*StreamResponse_ClientMessage
	//	*StreamResponse_ServerShutdown
	Event                isStreamResponse_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{11}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isStreamResponse_Event interface {
	isStreamResponse_Event()
}

type StreamResponse_ClientLogin struct {
	ClientLogin *Login `protobuf:"bytes,2,opt,name=client_login,json=clientLogin,proto3,oneof"`
}

type StreamResponse_ClientLogout struct {
	ClientLogout *Logout `protobuf:"bytes,3,opt,name=client_logout,json=clientLogout,proto3,oneof"`
}

type StreamResponse_ClientMessage struct {
	ClientMessage *Message `protobuf:"bytes,4,opt,name=client_message,json=clientMessage,proto3,oneof"`
}

type StreamResponse_ServerShutdown struct {
	ServerShutdown *Shutdown `protobuf:"bytes,5,opt,name=server_shutdown,json=serverShutdown,proto3,oneof"`
}

func (*StreamResponse_ClientLogin) isStreamResponse_Event() {}

func (*StreamResponse_ClientLogout) isStreamResponse_Event() {}

func (*StreamResponse_ClientMessage) isStreamResponse_Event() {}

func (*StreamResponse_ServerShutdown) isStreamResponse_Event() {}

func (m *StreamResponse) GetEvent() isStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StreamResponse) GetClientLogin() *Login {
	if x, ok := m.GetEvent().(*StreamResponse_ClientLogin); ok {
		return x.ClientLogin
	}
	return nil
}

func (m *StreamResponse) GetClientLogout() *Logout {
	if x, ok := m.GetEvent().(*StreamResponse_ClientLogout); ok {
		return x.ClientLogout
	}
	return nil
}

func (m *StreamResponse) GetClientMessage() *Message {
	if x, ok := m.GetEvent().(*StreamResponse_ClientMessage); ok {
		return x.ClientMessage
	}
	return nil
}

func (m *StreamResponse) GetServerShutdown() *Shutdown {
	if x, ok := m.GetEvent().(*StreamResponse_ServerShutdown); ok {
		return x.ServerShutdown
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamResponse_ClientLogin)(nil),
		(*StreamResponse_ClientLogout)(nil),
		(*StreamResponse_ClientMessage)(nil),
		(*StreamResponse_ServerShutdown)(nil),
	}
}

type RoomMeta struct {
	PlayerState          PlayerStates `protobuf:"varint,1,opt,name=playerState,proto3,enum=cloudwalker.PlayerStates" json:"playerState,omitempty"`
	Url                  string       `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title                string       `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle             string       `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	CurrentPosition      int64        `protobuf:"varint,5,opt,name=currentPosition,proto3" json:"currentPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RoomMeta) Reset()         { *m = RoomMeta{} }
func (m *RoomMeta) String() string { return proto.CompactTextString(m) }
func (*RoomMeta) ProtoMessage()    {}
func (*RoomMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{12}
}

func (m *RoomMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMeta.Unmarshal(m, b)
}
func (m *RoomMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMeta.Marshal(b, m, deterministic)
}
func (m *RoomMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMeta.Merge(m, src)
}
func (m *RoomMeta) XXX_Size() int {
	return xxx_messageInfo_RoomMeta.Size(m)
}
func (m *RoomMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMeta proto.InternalMessageInfo

func (m *RoomMeta) GetPlayerState() PlayerStates {
	if m != nil {
		return m.PlayerState
	}
	return PlayerStates_UNRECOGNISED
}

func (m *RoomMeta) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RoomMeta) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RoomMeta) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *RoomMeta) GetCurrentPosition() int64 {
	if m != nil {
		return m.CurrentPosition
	}
	return 0
}

type Login struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{13}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Logout struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout) Reset()         { *m = Logout{} }
func (m *Logout) String() string { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()    {}
func (*Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{14}
}

func (m *Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout.Unmarshal(m, b)
}
func (m *Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout.Marshal(b, m, deterministic)
}
func (m *Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout.Merge(m, src)
}
func (m *Logout) XXX_Size() int {
	return xxx_messageInfo_Logout.Size(m)
}
func (m *Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Logout proto.InternalMessageInfo

func (m *Logout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Message struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RoomMeta             *RoomMeta `protobuf:"bytes,2,opt,name=roomMeta,proto3" json:"roomMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{15}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetRoomMeta() *RoomMeta {
	if m != nil {
		return m.RoomMeta
	}
	return nil
}

type Shutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shutdown) Reset()         { *m = Shutdown{} }
func (m *Shutdown) String() string { return proto.CompactTextString(m) }
func (*Shutdown) ProtoMessage()    {}
func (*Shutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7fe98416ca281a, []int{16}
}

func (m *Shutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shutdown.Unmarshal(m, b)
}
func (m *Shutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shutdown.Marshal(b, m, deterministic)
}
func (m *Shutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shutdown.Merge(m, src)
}
func (m *Shutdown) XXX_Size() int {
	return xxx_messageInfo_Shutdown.Size(m)
}
func (m *Shutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_Shutdown.DiscardUnknown(m)
}

var xxx_messageInfo_Shutdown proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cloudwalker.JoinState", JoinState_name, JoinState_value)
	proto.RegisterEnum("cloudwalker.PlayerStates", PlayerStates_name, PlayerStates_value)
	proto.RegisterEnum("cloudwalker.LeaveRoomResponse_LeaveRoomState", LeaveRoomResponse_LeaveRoomState_name, LeaveRoomResponse_LeaveRoomState_value)
	proto.RegisterType((*LeaveRoomRequest)(nil), "cloudwalker.LeaveRoomRequest")
	proto.RegisterType((*LeaveRoomResponse)(nil), "cloudwalker.LeaveRoomResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "cloudwalker.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "cloudwalker.JoinRoomResponse")
	proto.RegisterType((*MakeRoomRequest)(nil), "cloudwalker.MakeRoomRequest")
	proto.RegisterType((*MakeRoomResponse)(nil), "cloudwalker.MakeRoomResponse")
	proto.RegisterType((*LoginRequest)(nil), "cloudwalker.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "cloudwalker.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "cloudwalker.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "cloudwalker.LogoutResponse")
	proto.RegisterType((*StreamRequest)(nil), "cloudwalker.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "cloudwalker.StreamResponse")
	proto.RegisterType((*RoomMeta)(nil), "cloudwalker.RoomMeta")
	proto.RegisterType((*Login)(nil), "cloudwalker.Login")
	proto.RegisterType((*Logout)(nil), "cloudwalker.Logout")
	proto.RegisterType((*Message)(nil), "cloudwalker.Message")
	proto.RegisterType((*Shutdown)(nil), "cloudwalker.Shutdown")
}

func init() {
	proto.RegisterFile("wewatch.proto", fileDescriptor_fa7fe98416ca281a)
}

var fileDescriptor_fa7fe98416ca281a = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0xb6, 0xf3, 0xd6, 0x64, 0x92, 0xa6, 0xcb, 0x52, 0x4e, 0xb9, 0xdc, 0x1d, 0x9c, 0x16, 0x21,
	0x55, 0x95, 0xc8, 0x41, 0x91, 0x78, 0x15, 0xd0, 0xb4, 0x71, 0xdb, 0x1c, 0x69, 0x12, 0x6d, 0x1a,
	0x42, 0x3f, 0x55, 0x6e, 0xb3, 0xf4, 0x4c, 0x1c, 0x6f, 0xb0, 0xd7, 0x8d, 0xf8, 0x5d, 0x88, 0x8f,
	0xfc, 0x00, 0x7e, 0x15, 0x68, 0xed, 0x5d, 0xc7, 0xf6, 0xa5, 0x27, 0xfc, 0xc9, 0xb3, 0x33, 0xf3,
	0xec, 0xce, 0xb3, 0xcf, 0xcc, 0xc2, 0xee, 0x9a, 0xad, 0x6d, 0x71, 0xf7, 0xa6, 0xb3, 0xf2, 0xb9,
	0xe0, 0xb8, 0x7e, 0xe7, 0xf2, 0x70, 0xbe, 0xb6, 0xdd, 0x05, 0xf3, 0xdb, 0x1f, 0xdd, 0x73, 0x7e,
	0xef, 0xb2, 0x57, 0x91, 0xeb, 0x36, 0xfc, 0xf5, 0x95, 0x70, 0x96, 0x2c, 0x10, 0xf6, 0x72, 0x15,
	0x47, 0x93, 0x63, 0x40, 0x03, 0x66, 0x3f, 0x30, 0xca, 0xf9, 0x92, 0xb2, 0xdf, 0x43, 0x16, 0x08,
	0xfc, 0x04, 0x2a, 0x3e, 0xe7, 0xcb, 0xfe, 0xbc, 0x65, 0xbe, 0x34, 0x0f, 0xca, 0x54, 0x59, 0x78,
	0x1f, 0xca, 0x82, 0x2f, 0x98, 0xd7, 0x2a, 0xbc, 0x34, 0x0f, 0x6a, 0x34, 0x36, 0xc8, 0x9f, 0x26,
	0xbc, 0x97, 0x82, 0x08, 0x56, 0xdc, 0x0b, 0x18, 0x9e, 0x42, 0xd3, 0xd5, 0x8b, 0x13, 0x61, 0x0b,
	0x16, 0x61, 0x35, 0x8f, 0x3e, 0xed, 0xa4, 0x8e, 0xd7, 0x79, 0x2b, 0x6f, 0xb3, 0x12, 0x25, 0xd1,
	0x1c, 0x08, 0x39, 0x87, 0x66, 0x36, 0x02, 0xd7, 0x61, 0x67, 0x3a, 0xfc, 0x69, 0x38, 0x9a, 0x0d,
	0x91, 0x21, 0x0d, 0x6a, 0x5d, 0x8e, 0x7e, 0xb6, 0x7a, 0xc8, 0x94, 0x46, 0x77, 0x40, 0xad, 0x6e,
	0xef, 0x1a, 0x15, 0x70, 0x13, 0x60, 0x38, 0xba, 0xba, 0xb1, 0x7e, 0xe9, 0x4f, 0xae, 0x26, 0xa8,
	0x48, 0x7e, 0x84, 0xbd, 0xd7, 0xdc, 0xf1, 0xd2, 0x65, 0x27, 0xe5, 0x99, 0xa9, 0xf2, 0x52, 0x64,
	0x14, 0xd2, 0x64, 0x90, 0xd7, 0x80, 0x36, 0x00, 0xaa, 0xe8, 0x2f, 0x01, 0x7e, 0xe3, 0x8e, 0x27,
	0xd2, 0x05, 0x3f, 0xc9, 0x14, 0x2c, 0x53, 0xe2, 0xca, 0x52, 0x91, 0xe4, 0x63, 0xd8, 0xbb, 0xb4,
	0x17, 0x99, 0x3b, 0x40, 0x50, 0x14, 0x0b, 0x7d, 0x14, 0xf9, 0x4b, 0x0e, 0x01, 0x6d, 0x82, 0xd4,
	0x86, 0x8f, 0xdc, 0x14, 0xf9, 0x01, 0x1a, 0x03, 0x7e, 0xef, 0x78, 0x1a, 0xad, 0x0d, 0xd5, 0x95,
	0x1d, 0x04, 0x6b, 0xee, 0xcf, 0x15, 0x64, 0x62, 0x63, 0x0c, 0x25, 0xcf, 0x5e, 0x32, 0x75, 0xa9,
	0xd1, 0x3f, 0xf9, 0x04, 0x76, 0x55, 0xbe, 0xda, 0x68, 0x2b, 0x37, 0x2a, 0x8c, 0x87, 0xe2, 0x9d,
	0x14, 0x12, 0x04, 0x4d, 0x1d, 0x16, 0xc3, 0x91, 0x13, 0xd8, 0x9d, 0x08, 0x9f, 0xd9, 0x49, 0xb9,
	0x9f, 0x43, 0x55, 0x1e, 0xfd, 0x92, 0x09, 0x3b, 0xca, 0xad, 0x1f, 0x7d, 0x90, 0xe1, 0x8d, 0x2a,
	0x27, 0x4d, 0xc2, 0xc8, 0x3f, 0x05, 0x68, 0x6a, 0x10, 0x75, 0xca, 0xaf, 0xa1, 0x96, 0xe8, 0x5b,
	0xc1, 0xb4, 0x3b, 0x71, 0x07, 0x74, 0x74, 0x07, 0x74, 0xae, 0x74, 0x04, 0xdd, 0x04, 0xe3, 0xaf,
	0xa0, 0x71, 0xe7, 0x3a, 0xcc, 0x13, 0x37, 0xae, 0xac, 0x3b, 0x22, 0xa3, 0x7e, 0x84, 0xb3, 0x62,
	0x95, 0x9e, 0x0b, 0x83, 0xd6, 0xe3, 0xc8, 0xc8, 0xc4, 0xdf, 0xc2, 0xee, 0x26, 0x91, 0x87, 0xa2,
	0x55, 0x8c, 0x32, 0xdf, 0xcf, 0x67, 0xf2, 0x50, 0x5c, 0x18, 0xb4, 0x91, 0xa4, 0xf2, 0x50, 0xe0,
	0xef, 0xa1, 0xa9, 0x72, 0x97, 0x2c, 0x08, 0xec, 0x7b, 0xd6, 0x2a, 0x45, 0xc9, 0xfb, 0x99, 0xe4,
	0xcb, 0xd8, 0x77, 0x61, 0x50, 0xb5, 0x93, 0x5a, 0xc0, 0xc7, 0xb0, 0x17, 0x30, 0xff, 0x81, 0xf9,
	0x37, 0xc1, 0x9b, 0x50, 0xcc, 0xf9, 0xda, 0x6b, 0x95, 0xb7, 0x50, 0x37, 0x51, 0xce, 0x0b, 0x83,
	0x36, 0xe3, 0x78, 0xbd, 0x72, 0xb2, 0x03, 0x65, 0xf6, 0xc0, 0x3c, 0x41, 0xfe, 0x32, 0xa1, 0xaa,
	0x29, 0xc6, 0xdf, 0x41, 0x7d, 0xe5, 0xda, 0x7f, 0x30, 0x3f, 0x2d, 0xe3, 0xa7, 0x19, 0xcc, 0xf1,
	0xc6, 0x1f, 0xd0, 0x74, 0xb4, 0xd4, 0x6d, 0xe8, 0xbb, 0x4a, 0x4c, 0xf2, 0x37, 0xd2, 0x84, 0x23,
	0x5c, 0x16, 0x31, 0x23, 0x35, 0x21, 0x0d, 0xa9, 0xc8, 0x20, 0xbc, 0x8d, 0x1d, 0xa5, 0x58, 0x91,
	0xda, 0xc6, 0x07, 0xb0, 0x77, 0x17, 0xfa, 0x3e, 0xf3, 0xc4, 0x98, 0x07, 0x8e, 0x70, 0x78, 0x5c,
	0x58, 0x91, 0xe6, 0x97, 0xc9, 0x33, 0x28, 0xc7, 0xd7, 0xa0, 0x45, 0x6c, 0xa6, 0x44, 0xfc, 0x1c,
	0x2a, 0x8a, 0xe8, 0x6d, 0xde, 0x31, 0xec, 0x68, 0x22, 0xb7, 0xb8, 0x33, 0x82, 0x2c, 0xfc, 0x3f,
	0x41, 0x02, 0x54, 0x35, 0xb3, 0x87, 0xdf, 0x40, 0x2d, 0x69, 0xf5, 0xf4, 0x20, 0x32, 0x70, 0x0d,
	0xca, 0xdd, 0x5e, 0x2f, 0x1a, 0x50, 0xfb, 0x9b, 0xd1, 0xf5, 0xaf, 0xfe, 0xcc, 0xc3, 0x39, 0x34,
	0xd2, 0xf4, 0x62, 0x04, 0x8d, 0xe9, 0x90, 0x5a, 0xa7, 0xa3, 0xf3, 0x61, 0x7f, 0x62, 0xf5, 0x90,
	0x81, 0xab, 0x50, 0x1a, 0x0f, 0xba, 0xd7, 0xc8, 0x94, 0x60, 0xe3, 0xee, 0x74, 0x62, 0xa1, 0x02,
	0x06, 0xa8, 0x50, 0x6b, 0xd6, 0x1f, 0xf6, 0x50, 0x51, 0x6e, 0x78, 0x36, 0xa2, 0xb3, 0x2e, 0xed,
	0xa1, 0x92, 0x74, 0x9c, 0x4c, 0xcf, 0xce, 0x2c, 0x8a, 0xca, 0x32, 0x73, 0x72, 0x3d, 0x3c, 0x45,
	0x95, 0xa3, 0xbf, 0x8b, 0xb0, 0x33, 0x63, 0x33, 0xf9, 0x6e, 0xe0, 0x63, 0xcd, 0xe2, 0xd3, 0xb7,
	0xf5, 0xae, 0x1a, 0xb4, 0xdd, 0xde, 0xe6, 0x52, 0xdd, 0x6c, 0xe0, 0xd3, 0x84, 0xea, 0xf6, 0x16,
	0xe1, 0x6b, 0x8c, 0x67, 0x5b, 0x7d, 0x09, 0xc8, 0x39, 0x54, 0xe2, 0x7e, 0xce, 0x81, 0x64, 0x26,
	0x45, 0x0e, 0x24, 0x3b, 0x00, 0x88, 0x71, 0x60, 0x7e, 0x66, 0xe2, 0x3e, 0x54, 0xf5, 0xa4, 0xc4,
	0xcf, 0xb3, 0xbd, 0x94, 0x9d, 0xb2, 0xed, 0x17, 0x8f, 0x78, 0x93, 0x33, 0xf5, 0xa1, 0xaa, 0xa7,
	0x7c, 0x0e, 0x2a, 0xf7, 0x7a, 0xe4, 0xa0, 0xf2, 0x4f, 0x03, 0x31, 0xf0, 0x00, 0x6a, 0xc9, 0xd3,
	0x85, 0x5f, 0x3c, 0xf6, 0x0c, 0xc6, 0x60, 0x1f, 0xbe, 0xfb, 0x95, 0x24, 0xc6, 0x6d, 0x25, 0x9a,
	0x67, 0x5f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xc5, 0x99, 0x33, 0xfd, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WeWatchClient is the client API for WeWatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeWatchClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (WeWatch_StreamClient, error)
	MakeRoom(ctx context.Context, in *MakeRoomRequest, opts ...grpc.CallOption) (*MakeRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResponse, error)
}

type weWatchClient struct {
	cc grpc.ClientConnInterface
}

func NewWeWatchClient(cc grpc.ClientConnInterface) WeWatchClient {
	return &weWatchClient{cc}
}

func (c *weWatchClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/cloudwalker.WeWatch/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weWatchClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/cloudwalker.WeWatch/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weWatchClient) Stream(ctx context.Context, opts ...grpc.CallOption) (WeWatch_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WeWatch_serviceDesc.Streams[0], "/cloudwalker.WeWatch/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &weWatchStreamClient{stream}
	return x, nil
}

type WeWatch_StreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type weWatchStreamClient struct {
	grpc.ClientStream
}

func (x *weWatchStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *weWatchStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *weWatchClient) MakeRoom(ctx context.Context, in *MakeRoomRequest, opts ...grpc.CallOption) (*MakeRoomResponse, error) {
	out := new(MakeRoomResponse)
	err := c.cc.Invoke(ctx, "/cloudwalker.WeWatch/MakeRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weWatchClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, "/cloudwalker.WeWatch/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weWatchClient) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResponse, error) {
	out := new(LeaveRoomResponse)
	err := c.cc.Invoke(ctx, "/cloudwalker.WeWatch/LeaveRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeWatchServer is the server API for WeWatch service.
type WeWatchServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Stream(WeWatch_StreamServer) error
	MakeRoom(context.Context, *MakeRoomRequest) (*MakeRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResponse, error)
}

// UnimplementedWeWatchServer can be embedded to have forward compatible implementations.
type UnimplementedWeWatchServer struct {
}

func (*UnimplementedWeWatchServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedWeWatchServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedWeWatchServer) Stream(srv WeWatch_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (*UnimplementedWeWatchServer) MakeRoom(ctx context.Context, req *MakeRoomRequest) (*MakeRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeRoom not implemented")
}
func (*UnimplementedWeWatchServer) JoinRoom(ctx context.Context, req *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (*UnimplementedWeWatchServer) LeaveRoom(ctx context.Context, req *LeaveRoomRequest) (*LeaveRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRoom not implemented")
}

func RegisterWeWatchServer(s *grpc.Server, srv WeWatchServer) {
	s.RegisterService(&_WeWatch_serviceDesc, srv)
}

func _WeWatch_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeWatchServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.WeWatch/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeWatchServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeWatch_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeWatchServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.WeWatch/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeWatchServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeWatch_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WeWatchServer).Stream(&weWatchStreamServer{stream})
}

type WeWatch_StreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type weWatchStreamServer struct {
	grpc.ServerStream
}

func (x *weWatchStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *weWatchStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WeWatch_MakeRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeWatchServer).MakeRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.WeWatch/MakeRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeWatchServer).MakeRoom(ctx, req.(*MakeRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeWatch_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeWatchServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.WeWatch/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeWatchServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeWatch_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeWatchServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.WeWatch/LeaveRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeWatchServer).LeaveRoom(ctx, req.(*LeaveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeWatch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudwalker.WeWatch",
	HandlerType: (*WeWatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _WeWatch_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _WeWatch_Logout_Handler,
		},
		{
			MethodName: "MakeRoom",
			Handler:    _WeWatch_MakeRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _WeWatch_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _WeWatch_LeaveRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _WeWatch_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wewatch.proto",
}
